version: 2
jobs:
  build:
    working_directory: ~/build
    parallelism: 2
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - setup_remote_docker
      - deploy:
            name: Build circleci-nodejs6.10
            command: |
              IMAGE_NAME=circleci-nodejs6.10
              if [ "${CIRCLE_BRANCH}" == "master" ]; then 
                echo ${CIRCLE_SHA1:0:7} > tag
                docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS quay.io
                docker build --rm=false -t quay.io/collectai/${IMAGE_NAME}:${CIRCLE_SHA1:0:7} .
                docker push quay.io/collectai/${IMAGE_NAME}:${CIRCLE_SHA1:0:7}
                docker tag quay.io/collectai/${IMAGE_NAME}:${CIRCLE_SHA1:0:7} quay.io/collectai/${IMAGE_NAME}:latest
                docker push quay.io/collectai/${IMAGE_NAME}:latest
              fi